<?php

namespace App\Models;

use App\Models\Scopes\GlobalScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PostsIfpe extends Model
{
    use HasFactory;
    protected $fillable = ['title','content','send_to','user_id','visible'];
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new GlobalScope());
    }

    public function deleteMany(Array $ids)
    {
        $posts = $this->whereIn('id',$ids)->update([
            'visible' => 0
        ]);
    }
    public function deleteOnly(Int $id)
    {
        $post = $this->findOrFail($id);
        $post->update([
            'visible' => false
        ]);
        return $post;
    }
}
